add_user/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^adduser/', include('adduser.urls', namespace="adduser")),
    url(r'^admin/', include(admin.site.urls)),
)

adduser/urls.py
from django.conf.urls import patterns, url
from adduser import views

urlpatterns= patterns('',
                      url(r'^$', views.index, name='index'),
                      url(r'^(?P<user_id>\d+)/$', views.detail, name='detail'),
                      url(r'^addnewuser', views.addnewuser, name='addnewuser'),
                      url(r'^edituser/(?P<user_id>\d+)', views.edituser, name='edituser'),
                      url(r'^deluser/(?P<user_id>\d+)', views.deluser, name='deluser')
)

adduser/models.py
# Create your models here.
from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=50,
                                  blank=False)
    last_name = models.CharField(max_length=50,
                                 blank=True)
    email = models.EmailField(max_length=200,
                              blank=True)
    def __str__(self):
        return self.first_name

adduser/forms.py
from django.forms import ModelForm
from adduser.models import User

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']

adduser/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from adduser.models import User
from adduser.forms import UserForm

def index(request):
    user_list = User.objects.all().order_by('last_name')
    context = {'user_list': user_list}
    return render(request, 'adduser/index.html', context)


def detail(request, user_id):
    userdetail = User.objects.get(pk=user_id)
    return render(request, 'adduser/detail.html', {'userdetail': userdetail})

def addnewuser(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/adduser')
    else:
        form = UserForm()

    return render(request, 'adduser/addnewuser.html', {'form': form})


def edituser(request, user_id):
    data = User.objects.get(pk=user_id)
    if request.method == "POST":
        form = UserForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/adduser/'+user_id)
    else:
        form = UserForm(instance=data)
    return render(request, 'adduser/edituser.html', {'form': form})


def deluser(request, user_id):
    d = User.objects.get(pk=user_id)
    d.delete()
    return HttpResponseRedirect('/adduser')

adduser/templates/adduser/addnewuser.html
<form method="POST" action="">
    {{ form }}
<input type="submit" value="Add user">
    </form>

adduser/templates/adduser/detail.html
<!DOCTYPE html>
<h1>{{ userdetail.first_name }} {{ userdetail.last_name }}</h1>
<p> {{ userdetail.email }}</p>
<p><a href="{% url 'adduser:edituser' userdetail.id %}"> Edit user details</a></p>
<p><a href="{% url 'adduser:deluser' userdetail.id %}"> Delete user</a></p>
<p><a href="{% url 'adduser:index' %}"> Return to user list</a></p>

adduser/templates/adduser/edituser.html
<!DOCTYPE html>
<form method="POST" action="">
    {{ form }}
<input type="submit" value="Edit User">
    </form>

adduser/templates/adduser/index.html
<!DOCTYPE html>
{% if user_list %}
    <ul>
    {% for user in user_list %}
        <li><a href="{% url 'adduser:detail' user.id %}">{{ user.first_name }} {{ user.last_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No users are listed.</p>
{% endif %}

<p><a href="{% url 'adduser:addnewuser' %}"> Add new user</a></p>